-- V1.0__create_base_tables.sql

-- Tabela bazowa dla użytkowników (kompletnych i niekompletnych)
CREATE TABLE incomplete_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone_number VARCHAR(15),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

-- Tabela dla pełnych użytkowników (dziedziczy po incomplete_users)
CREATE TABLE users (
    id BIGINT NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    password VARCHAR(120) NOT NULL,
    verified BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES incomplete_users(id) ON DELETE CASCADE
);

-- Tabela ról użytkowników
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role),
    FOREIGN KEY (user_id) REFERENCES incomplete_users(id) ON DELETE CASCADE
);

-- Tabela tokenów weryfikacyjnych
CREATE TABLE verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);