CREATE TABLE user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(40) NOT NULL,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    user_name VARCHAR(40) NOT NULL,
    phone_number VARCHAR(9) NOT NULL,
    verified BOOLEAN NOT NULL,
    role VARCHAR(20) NOT NULL,
    createdat DATETIME NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (username)
);