-- Create the base user table (parent class)
CREATE TABLE incomplete_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(50) NOT NULL,
    phone_number VARCHAR(15),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (email)
);

-- Create the users table (child class)
CREATE TABLE users (
    id BIGINT NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    password VARCHAR(120) NOT NULL,
    verified BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES incomplete_users(id) ON DELETE CASCADE
);

-- Create user roles table
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role),
    FOREIGN KEY (user_id) REFERENCES incomplete_users(id) ON DELETE CASCADE
);