CREATE TABLE bicycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    frame_number VARCHAR(20),
    brand VARCHAR(20) NOT NULL,
    model VARCHAR(40),
    type VARCHAR(40),
    frame_material VARCHAR(100),
    owner_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    production_date DATE,
    photo BYTEA,
    PRIMARY KEY (id),
    UNIQUE (frame_number),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);