CREATE TABLE bike_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    email VARCHAR(100) UNIQUE,
    website VARCHAR(255),
    street VARCHAR(255),
    building VARCHAR(20),
    flat VARCHAR(20),
    postal_code VARCHAR(10),
    city VARCHAR(100),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    phone_number VARCHAR(15),
    business_phone VARCHAR(15),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);


SELECT setval('bike_services_id_seq', 1);