-- Create service packages table
CREATE TABLE service_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    price DECIMAL(10,2) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    display_order INT,
    service_id BIGINT,
    PRIMARY KEY (id)
);

-- Create service package features table
CREATE TABLE service_package_features (
    package_id BIGINT NOT NULL,
    feature VARCHAR(500) NOT NULL,
    PRIMARY KEY (package_id, feature),
    FOREIGN KEY (package_id) REFERENCES service_packages(id) ON DELETE CASCADE
);

-- Create service records table
CREATE TABLE service_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    service_date DATE NOT NULL,
    price DECIMAL(10, 2),
    PRIMARY KEY (id),
    FOREIGN KEY (bicycle_id) REFERENCES bicycles(id)
);

-- Create service orders table
CREATE TABLE service_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    service_package_id BIGINT,
    service_package_code VARCHAR(20),
    pickup_date DATE NOT NULL,
    pickup_address VARCHAR(255) NOT NULL,
    pickup_latitude DECIMAL(10,8),
    pickup_longitude DECIMAL(11,8),
    price DECIMAL(10,2) NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT NOW(),
    additional_notes VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    service_notes VARCHAR(500),
    PRIMARY KEY (id),
    FOREIGN KEY (bicycle_id) REFERENCES incomplete_bikes(id),
    FOREIGN KEY (user_id) REFERENCES incomplete_users(id),
    FOREIGN KEY (service_package_id) REFERENCES service_packages(id)
);

-- Create indexes for faster lookups
CREATE INDEX idx_service_packages_code ON service_packages(code);
CREATE INDEX idx_service_packages_active ON service_packages(active);
CREATE INDEX idx_service_orders_bicycle ON service_orders(bicycle_id);
CREATE INDEX idx_service_orders_user ON service_orders(user_id);
CREATE INDEX idx_service_orders_service_package ON service_orders(service_package_id);
CREATE INDEX idx_service_orders_status ON service_orders(status);
CREATE INDEX idx_service_orders_pickup_date ON service_orders(pickup_date);