
CREATE TABLE bike_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(255) NOT NULL,
    postal_code VARCHAR(10),
    city VARCHAR(20),
    phone_number VARCHAR(15),
    email VARCHAR(50) NOT NULL,
    password VARCHAR(120) NOT NULL,
    opening_hours JSONB,
    description TEXT,
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (email)
);