-- V1.3__create_service_package_tables.sql

-- Tabela pakietów serwisowych
CREATE TABLE service_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    price DECIMAL(10,2) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    display_order INT,
    service_id BIGINT,
    PRIMARY KEY (id)
);

-- Tabela cech pakietów serwisowych
CREATE TABLE service_package_features (
    package_id BIGINT NOT NULL,
    feature VARCHAR(500) NOT NULL,
    PRIMARY KEY (package_id, feature),
    FOREIGN KEY (package_id) REFERENCES service_packages(id) ON DELETE CASCADE
);