-- Tworzenie tabeli dla tokenów weryfikacyjnych
CREATE TABLE verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id),
    UNIQUE (token),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Dodanie indeksu dla szybszego wyszukiwania po tokenie
CREATE INDEX idx_tokens_token ON verification_tokens(token);
