CREATE TABLE opening_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    monday VARCHAR(50),
    tuesday VARCHAR(50),
    wednesday VARCHAR(50),
    thursday VARCHAR(50),
    friday VARCHAR(50),
    saturday VARCHAR(50),
    sunday VARCHAR(50),
    bike_service_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (bike_service_id) REFERENCES bike_services(id) ON DELETE CASCADE
);