CREATE TABLE bicycle_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id BIGINT NOT NULL,
    photo_data BYTEA,
    content_type VARCHAR(100),
    file_size BIGINT,
    uploaded_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (bicycle_id) REFERENCES bicycles(id) ON DELETE CASCADE,
    CONSTRAINT unique_bicycle_photo UNIQUE (bicycle_id)
);


ALTER TABLE bicycles DROP COLUMN IF EXISTS photo;