CREATE TABLE service_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    service_date DATE NOT NULL,
    price DECIMAL(10, 2),
    PRIMARY KEY (id),
    FOREIGN KEY (bicycle_id) REFERENCES bicycles(id)
);