-- Tworzenie tabeli konfiguracji slotów serwisowych
CREATE TABLE service_slot_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_date DATE NOT NULL,
    end_date DATE,
    max_bikes_per_day INT NOT NULL,
    max_bikes_per_order INT,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    PRIMARY KEY (id)
);

-- Dodanie indeksu dla szybszego wyszukiwania po datach
CREATE INDEX idx_slot_config_dates ON service_slot_configs(start_date, end_date);

-- Wstawienie domyślnej konfiguracji (5 rowerów dziennie, max 3 na zamówienie)
INSERT INTO service_slot_configs (start_date, end_date, max_bikes_per_day, max_bikes_per_order, created_at)
VALUES (CURRENT_DATE, NULL, 5, 3, CURRENT_DATE);

-- Dodanie komentarzy do tabeli
COMMENT ON TABLE service_slot_configs IS 'Konfiguracje dostępności slotów serwisowych w czasie';
COMMENT ON COLUMN service_slot_configs.start_date IS 'Data początkowa okresu obowiązywania konfiguracji';
COMMENT ON COLUMN service_slot_configs.end_date IS 'Data końcowa okresu obowiązywania konfiguracji (NULL oznacza bezterminowo)';
COMMENT ON COLUMN service_slot_configs.max_bikes_per_day IS 'Maksymalna liczba rowerów, które warsztat może obsłużyć danego dnia';
COMMENT ON COLUMN service_slot_configs.max_bikes_per_order IS 'Maksymalna liczba rowerów w jednym zamówieniu (NULL = równa max_bikes_per_day)';