CREATE TABLE service_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    service_package_id BIGINT,
    service_package_code VARCHAR(20),
    pickup_date DATE NOT NULL,
    pickup_address VARCHAR(255) NOT NULL,
    pickup_latitude DECIMAL(10,8),
    pickup_longitude DECIMAL(11,8),
    price DECIMAL(10,2) NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT NOW(),
    additional_notes VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    service_notes VARCHAR(500),
    PRIMARY KEY (id),
    FOREIGN KEY (bicycle_id) REFERENCES incomplete_bikes(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (service_package_id) REFERENCES service_packages(id)
);

-- Indeksy dla szybszego wyszukiwania
CREATE INDEX idx_service_orders_bicycle ON service_orders(bicycle_id);
CREATE INDEX idx_service_orders_user ON service_orders(user_id);
CREATE INDEX idx_service_orders_service_package ON service_orders(service_package_id);
CREATE INDEX idx_service_orders_status ON service_orders(status);
CREATE INDEX idx_service_orders_pickup_date ON service_orders(pickup_date);