CREATE TABLE bicycle_enumerations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE bicycle_enumeration_values (
    enumeration_id BIGINT NOT NULL,
    value VARCHAR(100) NOT NULL,
    PRIMARY KEY (enumeration_id, value),
    FOREIGN KEY (enumeration_id) REFERENCES bicycle_enumerations(id) ON DELETE CASCADE
);

-- Dodanie indeksu dla szybkiego wyszukiwania po typie
CREATE INDEX idx_bicycle_enumerations_type ON bicycle_enumerations(type);