CREATE TABLE service_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bicycle_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    service_package VARCHAR(20) NOT NULL,
    pickup_date DATE NOT NULL,
    pickup_address VARCHAR(255) NOT NULL,
    pickup_latitude DECIMAL(10,8),
    pickup_longitude DECIMAL(11,8),
    price DECIMAL(10,2) NOT NULL,
    order_date TIMESTAMP NOT NULL,
    additional_notes VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    service_notes VARCHAR(500),
    PRIMARY KEY (id),
    FOREIGN KEY (bicycle_id) REFERENCES bicycles(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (service_id) REFERENCES bike_services(id)
);

-- Indeksy dla szybszego wyszukiwania
CREATE INDEX idx_service_orders_bicycle ON service_orders(bicycle_id);
CREATE INDEX idx_service_orders_user ON service_orders(user_id);
CREATE INDEX idx_service_orders_service ON service_orders(service_id);
CREATE INDEX idx_service_orders_status ON service_orders(status);
CREATE INDEX idx_service_orders_pickup_date ON service_orders(pickup_date);