
CREATE TABLE incomplete_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(50) NOT NULL,
    phone_number VARCHAR(15),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (email)
);

-- Kopiowanie danych z tabeli users do incomplete_users
INSERT INTO incomplete_users (id, email, phone_number, created_at)
SELECT id, email, phone_number, created_at FROM users;

-- Modyfikacja tabeli users - usunięcie kolumn, które zostały przeniesione do incomplete_users
ALTER TABLE users DROP COLUMN email;
ALTER TABLE users DROP COLUMN phone_number;
ALTER TABLE users DROP COLUMN created_at;

-- Dodanie klucza obcego do tabeli users, łączącego z incomplete_users
ALTER TABLE users ADD CONSTRAINT fk_incomplete_user FOREIGN KEY (id) REFERENCES incomplete_users(id) ON DELETE CASCADE;

-- Aktualizacja relacji w tabeli incomplete_bikes
ALTER TABLE incomplete_bikes DROP CONSTRAINT fk_owner;
ALTER TABLE incomplete_bikes ADD CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES incomplete_users(id);

-- Aktualizacja relacji w tabeli user_roles
ALTER TABLE user_roles DROP CONSTRAINT fk_user_roles_user_id;
ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES incomplete_users(id);